#!/bin/bash
# Fetches the official sentry-godot GDExtension into graphics/addons/sentry and writes
# graphics/override.cfg with the Sentry DSN (no-op unless SENTRY_DSN is set). The addon's
# .so/.dll loads on Windows/macOS/glibc via its .gdextension; on musl the addon is inert —
# `gd` ignores .gdextension addons there (Sentry is statically linked, see internal/sentry)
# and only override.cfg's DSN matters.
#
# graphics/addons/sentry and graphics/override.cfg are gitignored, so this is only active for
# OUR official builds: forks that don't set SENTRY_DSN build with no crash reporting.
#
#   SENTRY_DSN          required to enable Sentry (Project Settings > Client Keys)
#
# Run before `gd build` (see deploy.sh) so the addon/override are embedded in the export pck.
set -euo pipefail

SENTRY_TAG="1.6.0"
SENTRY_ASSET="sentry-godot-1.6.0+4e3e3e5.zip"   # GitHub release asset (commit-suffixed)
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ADDON_DIR="$ROOT/graphics/addons/sentry"
OVERRIDE="$ROOT/graphics/override.cfg"
CACHE="$ROOT/releases/.cache/${SENTRY_ASSET}"

if [ -z "${SENTRY_DSN:-}" ]; then
  echo "fetch_sentry: SENTRY_DSN not set — building without Sentry."
  rm -rf "$ADDON_DIR" "$OVERRIDE"
  exit 0
fi

if [ ! -f "$ADDON_DIR/sentry.gdextension" ]; then
  echo "fetch_sentry: downloading sentry-godot ${SENTRY_TAG}..."
  mkdir -p "$(dirname "$CACHE")"
  [ -f "$CACHE" ] || curl -fsSL -o "$CACHE" \
    "https://github.com/getsentry/sentry-godot/releases/download/${SENTRY_TAG}/${SENTRY_ASSET}"
  # Archive root is addons/sentry/, so extract as-is into graphics/ (no "*" filter:
  # some unzip builds won't recurse it).
  unzip -oq "$CACHE" -d "$ROOT/graphics"
fi

# DSN + metadata baked into the export pck (res://override.cfg), read at startup;
# overrides ProjectSettings without touching the committed project.godot.
VERSION="$(grep -oP 'config/version="\K[^"]+' "$ROOT/graphics/project.godot" 2>/dev/null || echo dev)"
cat > "$OVERRIDE" <<EOF
; Generated by fetch_sentry.sh — DO NOT COMMIT (gitignored).
[sentry]

options/dsn="${SENTRY_DSN}"
EOF

echo "fetch_sentry: configured Sentry (release aviary@${VERSION}, env ${SENTRY_ENVIRONMENT:-production})."
