#!/bin/bash
# Bakes $SENTRY_DSN (and $AVIARY_VERSION, the release/velopack version) into the build by
# generating internal/sentry/dsn_injected.go (gitignored), which sets the package's `dsn` and
# `version` vars. No SENTRY_DSN → removes it → dsn stays empty → Sentry disabled (the build
# still compiles and runs). The DSN is never committed. Run before `gd build` (see deploy.sh).
set -euo pipefail

OUT="$(cd "$(dirname "$0")" && pwd)/dsn_injected.go"

if [ -z "${SENTRY_DSN:-}" ]; then
  rm -f "$OUT"
  echo "inject_dsn: SENTRY_DSN not set — Sentry disabled."
  exit 0
fi

cat > "$OUT" <<EOF
// Code generated by inject_dsn.sh — DO NOT EDIT or COMMIT (gitignored).
package sentry

func init() {
	dsn = "${SENTRY_DSN}"
	version = "${AVIARY_VERSION:-}"
}
EOF
echo "inject_dsn: baked Sentry DSN${AVIARY_VERSION:+ + version $AVIARY_VERSION} into dsn_injected.go."
